# Generated by Django 5.1.1 on 2024-12-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_post_mastery_remove_user_post_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_post',
            name='title',
            field=models.CharField(default='Untitled', max_length=50),
        ),
    ]
